CREATE DATABASE IF NOT EXISTS payments_db CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
USE payments_db;

CREATE TABLE IF NOT EXISTS pago (
  id CHAR(36) PRIMARY KEY,
  monto DECIMAL(12,2) NOT NULL,
  moneda VARCHAR(8) NOT NULL,
  estado VARCHAR(32) NOT NULL,
  pasarela VARCHAR(32) NOT NULL,
  referencia_pasarela VARCHAR(128),
  creado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  actualizado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS metodo_pago_guardado (
  id CHAR(36) PRIMARY KEY,
  auth_user_id CHAR(36),
  email_usuario VARCHAR(255) NOT NULL,
  marca VARCHAR(64),
  ultimos4 VARCHAR(8),
  tokenizado VARCHAR(255),
  creado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_metodo_email (email_usuario)
);

CREATE TABLE IF NOT EXISTS transaccion_pasarela (
  id CHAR(36) PRIMARY KEY,
  pago_id CHAR(36) NOT NULL,
  pasarela VARCHAR(32) NOT NULL,
  estado VARCHAR(32) NOT NULL,
  referencia_externa VARCHAR(128),
  respuesta_cruda TEXT,
  creado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_tx_pago FOREIGN KEY (pago_id) REFERENCES pago(id)
);

CREATE TABLE IF NOT EXISTS outbox (
  id CHAR(36) PRIMARY KEY,
  type VARCHAR(128) NOT NULL,
  routing_key VARCHAR(256) NOT NULL,
  payload TEXT NOT NULL,
  creado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  publicado TINYINT(1) NOT NULL DEFAULT 0,
  publicado_en TIMESTAMP NULL
);
